FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY client ./client
COPY shared ./shared

RUN pnpm install --frozen-lockfile

EXPOSE 5173

ENV VITE_API_URL=http://localhost:3000

CMD ["pnpm", "dev", "--prefix", "client"]
