FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY server ./server
COPY shared ./shared

RUN pnpm install --frozen-lockfile

EXPOSE 3000

ENV NODE_ENV=development

CMD ["pnpm", "dev", "--prefix", "server"]
